### PR TITLE
Fix Frame.sp() in GDB

### LINKED ISSUE #3587: pwndbg.dbg_mod.Frame.sp() and .start() are borked
### Description

They return different things between LLDB and GDB, there is some duplication, bug fixes needed etc. Needs to be investigated.

### PR DESCRIPTION
**Pull request by k4lizen**
+ [x] I read the contributing documentation.
+ [x] I am providing a screenshot of the (new feature) / (fixed bug).

Fixes: https://github.com/pwndbg/pwndbg/issues/3587 and https://github.com/pwndbg/pwndbg/issues/3588

The stack offsets line up now.
image
image

### CODE REVIEW

File: setup.sh [hunk 1]
```diff
@@ -215,7 +215,7 @@ pip install uv
 
 # Install dependencies
 echo "Installing dependencies.."
-uv sync --extra gdb --extra lldb --quiet
```
Comment (disconnect3d) [inline setup.sh:218]: Is this a change we want to make?

Comment (k4lizen) [reply setup.sh:218]: ye, the initial reasoning for adding that was because the sync was quick and cluttered the output, but it can be very long now so its better to see it
